*** Starting uWSGI 2.0.15 (64bit) on [Sun Dec 17 18:17:48 2017] ***
compiled with version: 5.4.0 20160609 on 17 December 2017 11:30:00
os: Linux-4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017
nodename: o-OwO-o
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/zwm/Workplace/SmartRailway/conf
writing pidfile to /home/zwm/Workplace/SmartRailway/log/uwsgi.pid
detected binary path: /home/zwm/Workplace/SmartRailway/venv-py3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 31023
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:9090 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:37675 (port auto-assigned) fd 3
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1f05df0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 268398 bytes (262 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1f05df0 pid: 4423 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 4423)
spawned uWSGI worker 1 (pid: 4428, cores: 1)
spawned uWSGI http 1 (pid: 4429)
[pid: 4428|app: 0|req: 1/1] 127.0.0.1 () {38 vars in 638 bytes} [Sun Dec 17 18:17:52 2017] GET / => generated 20 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[pid: 4428|app: 0|req: 2/2] 127.0.0.1 () {36 vars in 586 bytes} [Sun Dec 17 18:17:52 2017] GET /favicon.ico => generated 233 bytes in 7 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 4428|app: 0|req: 3/3] 127.0.0.1 () {38 vars in 638 bytes} [Sun Dec 17 18:17:53 2017] GET / => generated 20 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[question] 开水

Answer:
{'answer': '#14', 'question': '开水'}
[pid: 4428|app: 0|req: 4/4] 127.0.0.1 () {36 vars in 674 bytes} [Sun Dec 17 18:18:08 2017] GET /answer?question=%E5%BC%80%E6%B0%B4 => generated 39 bytes in 26 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[question] 开水

Answer:
{'answer': '#14', 'question': '开水'}
[pid: 4428|app: 0|req: 5/5] 127.0.0.1 () {38 vars in 705 bytes} [Sun Dec 17 18:18:11 2017] GET /answer?question=%E5%BC%80%E6%B0%B4 => generated 39 bytes in 26 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 4429)
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.15 (64bit) on [Sun Dec 17 18:19:09 2017] ***
compiled with version: 5.4.0 20160609 on 17 December 2017 11:30:00
os: Linux-4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017
nodename: o-OwO-o
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/zwm/Workplace/SmartRailway/conf
writing pidfile to /home/zwm/Workplace/SmartRailway/log/uwsgi.pid
detected binary path: /home/zwm/Workplace/SmartRailway/venv-py3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 31023
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:9090 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:39527 (port auto-assigned) fd 3
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x863df0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 268398 bytes (262 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x863df0 pid: 4477 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 4477)
spawned uWSGI worker 1 (pid: 4482, cores: 1)
spawned uWSGI http 1 (pid: 4483)
[question] 开水
[pid: 4482|app: 0|req: 1/1] 127.0.0.1 () {38 vars in 705 bytes} [Sun Dec 17 18:19:11 2017] GET /answer?question=%E5%BC%80%E6%B0%B4 => generated 39 bytes in 28 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[question] 
	[proc_synonym]   -> []
MaxSimIndex_list []
[pid: 4482|app: 0|req: 2/2] 127.0.0.1 () {44 vars in 739 bytes} [Sun Dec 17 18:21:34 2017] POST /answer => generated 2 bytes in 55 msecs (HTTP/1.1 200) 2 headers in 78 bytes (1 switches on core 0)
[question] 开水
[pid: 4482|app: 0|req: 3/3] 127.0.0.1 () {36 vars in 672 bytes} [Sun Dec 17 18:21:40 2017] GET /answer?question=%E5%BC%80%E6%B0%B4 => generated 39 bytes in 21 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 4483)
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.15 (64bit) on [Sun Dec 17 18:22:38 2017] ***
compiled with version: 5.4.0 20160609 on 17 December 2017 11:30:00
os: Linux-4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017
nodename: o-OwO-o
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/zwm/Workplace/SmartRailway/conf
writing pidfile to /home/zwm/Workplace/SmartRailway/log/uwsgi.pid
detected binary path: /home/zwm/Workplace/SmartRailway/venv-py3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 31023
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:9090 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:42655 (port auto-assigned) fd 3
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1220df0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 268398 bytes (262 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1220df0 pid: 5056 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 5056)
spawned uWSGI worker 1 (pid: 5067, cores: 1)
spawned uWSGI http 1 (pid: 5068)
[question] 开水
[pid: 5067|app: 0|req: 1/1] 127.0.0.1 () {44 vars in 738 bytes} [Sun Dec 17 18:22:51 2017] POST /answer => generated 39 bytes in 26 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[question] 开水
[pid: 5067|app: 0|req: 2/2] 127.0.0.1 () {36 vars in 673 bytes} [Sun Dec 17 18:22:55 2017] GET /answer?question=%E5%BC%80%E6%B0%B4 => generated 39 bytes in 22 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[question] 去哪里买票
MaxSimIndex_list [15, 436, 274]
[pid: 5067|app: 0|req: 3/3] 127.0.0.1 () {44 vars in 739 bytes} [Sun Dec 17 18:23:04 2017] POST /answer => generated 791 bytes in 117 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[question] 去哪里买票
MaxSimIndex_list [15, 436, 274]
[pid: 5067|app: 0|req: 4/4] 127.0.0.1 () {36 vars in 728 bytes} [Sun Dec 17 18:23:13 2017] GET /answer?question=%E5%8E%BB%E5%93%AA%E9%87%8C%E4%B9%B0%E7%A5%A8 => generated 791 bytes in 54 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 5068)
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.15 (64bit) on [Sun Dec 17 18:34:00 2017] ***
compiled with version: 5.4.0 20160609 on 17 December 2017 11:30:00
os: Linux-4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017
nodename: o-OwO-o
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/zwm/Workplace/SmartRailway/conf
writing pidfile to /home/zwm/Workplace/SmartRailway/log/uwsgi.pid
detected binary path: /home/zwm/Workplace/SmartRailway/venv-py3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 31023
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:41999 (port auto-assigned) fd 3
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1f59df0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 268398 bytes (262 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1f59df0 pid: 5318 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 5318)
spawned uWSGI worker 1 (pid: 5324, cores: 1)
spawned uWSGI http 1 (pid: 5325)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 5325)
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.15 (64bit) on [Sun Dec 17 18:34:30 2017] ***
compiled with version: 5.4.0 20160609 on 17 December 2017 11:30:00
os: Linux-4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017
nodename: o-OwO-o
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/zwm/Workplace/SmartRailway/conf
writing pidfile to /home/zwm/Workplace/SmartRailway/log/uwsgi.pid
detected binary path: /home/zwm/Workplace/SmartRailway/venv-py3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 31023
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:5000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:43429 (port auto-assigned) fd 3
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1214df0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 268398 bytes (262 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1214df0 pid: 5337 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 5337)
spawned uWSGI worker 1 (pid: 5342, cores: 1)
spawned uWSGI http 1 (pid: 5343)
[question] 开水
[pid: 5342|app: 0|req: 1/1] 127.0.0.1 () {44 vars in 753 bytes} [Sun Dec 17 18:34:32 2017] POST /smartQuestion => generated 39 bytes in 27 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[pid: 5342|app: 0|req: 2/2] 127.0.0.1 () {38 vars in 637 bytes} [Sun Dec 17 18:54:13 2017] GET / => generated 20 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.15 (64bit) on [Sat Jan 13 14:14:54 2018] ***
compiled with version: 5.4.0 20160609 on 17 December 2017 11:30:00
os: Linux-4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018
nodename: o-OwO-o
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/zwm/Workplace/SmartStation/flask/conf
writing pidfile to /home/zwm/Workplace/SmartStation/flask/log/uwsgi.pid
detected binary path: /home/zwm/Workplace/SmartStation/venv-py3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 30992
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:5000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:46485 (port auto-assigned) fd 3
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x204ee60
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 670995 bytes (655 KB) for 4 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "../src/main.py", line 1, in <module>
    from flask import Flask
ImportError: No module named 'flask'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 16269)
spawned uWSGI worker 1 (pid: 16270, cores: 1)
spawned uWSGI worker 2 (pid: 16271, cores: 1)
spawned uWSGI worker 3 (pid: 16272, cores: 1)
spawned uWSGI worker 4 (pid: 16273, cores: 1)
spawned uWSGI http 1 (pid: 16274)
--- no python application found, check your startup logs for errors ---
[pid: 16271|app: -1|req: -1/1] 127.0.0.1 () {36 vars in 608 bytes} [Sat Jan 13 14:15:36 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 16272|app: -1|req: -1/2] 127.0.0.1 () {36 vars in 587 bytes} [Sat Jan 13 14:15:36 2018] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 16274)
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.15 (64bit) on [Sat Jan 13 14:16:54 2018] ***
compiled with version: 5.4.0 20160609 on 17 December 2017 11:30:00
os: Linux-4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018
nodename: o-OwO-o
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/zwm/Workplace/SmartStation/flask/conf
writing pidfile to /home/zwm/Workplace/SmartStation/flask/log/uwsgi.pid
detected binary path: /home/zwm/Workplace/SmartStation/venv-py3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 30992
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:5000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:39665 (port auto-assigned) fd 3
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1122e80
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 670995 bytes (655 KB) for 4 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "/home/zwm/Workplace/SmartStation/flask/src/main.py", line 1, in <module>
    from flask import Flask
ImportError: No module named 'flask'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 16549)
spawned uWSGI worker 1 (pid: 16550, cores: 1)
spawned uWSGI worker 2 (pid: 16551, cores: 1)
spawned uWSGI worker 3 (pid: 16552, cores: 1)
spawned uWSGI worker 4 (pid: 16553, cores: 1)
spawned uWSGI http 1 (pid: 16554)
--- no python application found, check your startup logs for errors ---
[pid: 16551|app: -1|req: -1/1] 127.0.0.1 () {38 vars in 639 bytes} [Sat Jan 13 14:17:01 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 16550|app: -1|req: -1/2] 127.0.0.1 () {40 vars in 640 bytes} [Sat Jan 13 14:17:01 2018] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 16551|app: -1|req: -1/3] 127.0.0.1 () {38 vars in 639 bytes} [Sat Jan 13 14:17:02 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 16551|app: -1|req: -1/4] 127.0.0.1 () {40 vars in 640 bytes} [Sat Jan 13 14:17:02 2018] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 16554)
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.15 (64bit) on [Sat Jan 13 14:18:00 2018] ***
compiled with version: 5.4.0 20160609 on 17 December 2017 11:30:00
os: Linux-4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018
nodename: o-OwO-o
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/zwm/Workplace/SmartStation/flask/conf
writing pidfile to /home/zwm/Workplace/SmartStation/flask/log/uwsgi.pid
detected binary path: /home/zwm/Workplace/SmartStation/venv-py3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 30992
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:5000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:45625 (port auto-assigned) fd 3
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xdd3e80
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 670995 bytes (655 KB) for 4 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "/home/zwm/Workplace/SmartStation/flask/src/main.py", line 1, in <module>
    from flask import Flask
ImportError: No module named 'flask'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 16718)
spawned uWSGI worker 1 (pid: 16719, cores: 1)
spawned uWSGI worker 2 (pid: 16720, cores: 1)
spawned uWSGI worker 3 (pid: 16721, cores: 1)
spawned uWSGI worker 4 (pid: 16722, cores: 1)
spawned uWSGI http 1 (pid: 16723)
--- no python application found, check your startup logs for errors ---
[pid: 16721|app: -1|req: -1/1] 127.0.0.1 () {38 vars in 638 bytes} [Sat Jan 13 14:18:03 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 16721|app: -1|req: -1/2] 127.0.0.1 () {40 vars in 639 bytes} [Sat Jan 13 14:18:03 2018] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.15 (64bit) on [Sat Jan 13 14:18:49 2018] ***
compiled with version: 5.4.0 20160609 on 17 December 2017 11:30:00
os: Linux-4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018
nodename: o-OwO-o
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/zwm/Workplace/SmartStation/flask/conf
writing pidfile to /home/zwm/Workplace/SmartStation/flask/log/uwsgi.pid
detected binary path: /home/zwm/Workplace/SmartStation/venv-py3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 30992
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (0.0.0.0:5000).
bind(): Address already in use [core/socket.c line 769]
Sat Jan 13 14:19:32 2018 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jan 13 14:19:32 2018 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jan 13 14:19:32 2018 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jan 13 14:19:32 2018 - uWSGI worker 4 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.15 (64bit) on [Sat Jan 13 14:19:41 2018] ***
compiled with version: 5.4.0 20160609 on 17 December 2017 11:30:00
os: Linux-4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018
nodename: o-OwO-o
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/zwm/Workplace/SmartStation/flask/conf
writing pidfile to /home/zwm/Workplace/SmartStation/flask/log/uwsgi.pid
detected binary path: /home/zwm/Workplace/SmartStation/venv-py3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 30992
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:5000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:36455 (port auto-assigned) fd 3
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x944e80
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 670995 bytes (655 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x944e80 pid: 16779 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 16779)
spawned uWSGI worker 1 (pid: 16784, cores: 1)
spawned uWSGI worker 2 (pid: 16785, cores: 1)
spawned uWSGI worker 3 (pid: 16786, cores: 1)
spawned uWSGI worker 4 (pid: 16787, cores: 1)
spawned uWSGI http 1 (pid: 16788)
[pid: 16784|app: 0|req: 1/1] 127.0.0.1 () {38 vars in 638 bytes} [Sat Jan 13 14:19:45 2018] GET / => generated 20 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[pid: 16784|app: 0|req: 2/2] 127.0.0.1 () {40 vars in 639 bytes} [Sat Jan 13 14:19:45 2018] GET /favicon.ico => generated 233 bytes in 13 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[question] None
[2018-01-13 14:19:58,052] ERROR in app: Exception on /smartQuestion [GET]
Traceback (most recent call last):
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zwm/Workplace/SmartStation/flask/src/main.py", line 27, in get_answer
    ans = answer(question)
  File "/home/zwm/Workplace/SmartStation/flask/src/qa.py", line 80, in answer
    segment = pynlpir.segment(question, pos_tagging=False) # 分词
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/pynlpir/__init__.py", line 232, in segment
    s = _decode(s)
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/pynlpir/__init__.py", line 164, in _decode
    return s if isinstance(s, unicode) else s.decode(encoding, errors)
AttributeError: 'NoneType' object has no attribute 'decode'
[pid: 16784|app: 0|req: 3/3] 127.0.0.1 () {36 vars in 729 bytes} [Sat Jan 13 14:19:58 2018] GET /smartQuestion?s=%E6%88%91%E7%88%B1%E4%BD%A0%E4%B8%AD%E5%9B%BD => generated 291 bytes in 27 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
[question] 我爱你中国
	[proc_synonym] 爱 -> []
	[proc_synonym] 中国 -> ['途中']
MaxSimIndex_list [105, 12, 108]
[pid: 16784|app: 0|req: 4/4] 127.0.0.1 () {36 vars in 743 bytes} [Sat Jan 13 14:20:42 2018] GET /smartQuestion?question=%E6%88%91%E7%88%B1%E4%BD%A0%E4%B8%AD%E5%9B%BD => generated 986 bytes in 198 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 16788)
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.15 (64bit) on [Sat Jan 13 22:57:00 2018] ***
compiled with version: 5.4.0 20160609 on 04 December 2017 23:48:23
os: Linux-4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017
nodename: o-ubuntu-o
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/zwm/Workplace/SmartStation/flask/conf
writing pidfile to /home/zwm/Workplace/SmartStation/flask/log/uwsgi.pid
detected binary path: /home/zwm/Workplace/SmartStation/venv-py3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 14759
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:5000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:41995 (port auto-assigned) fd 3
Python version: 3.5.2 (default, Sep 14 2017, 22:51:06)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x913100
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 670995 bytes (655 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x913100 pid: 6028 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 6028)
spawned uWSGI worker 1 (pid: 6031, cores: 1)
spawned uWSGI worker 2 (pid: 6032, cores: 1)
spawned uWSGI worker 3 (pid: 6033, cores: 1)
spawned uWSGI worker 4 (pid: 6034, cores: 1)
spawned uWSGI http 1 (pid: 6035)
[pid: 6032|app: 0|req: 1/1] 127.0.0.1 () {36 vars in 610 bytes} [Sat Jan 13 22:57:37 2018] GET / => generated 20 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[pid: 6031|app: 0|req: 1/2] 127.0.0.1 () {36 vars in 589 bytes} [Sat Jan 13 22:57:37 2018] GET /favicon.ico => generated 233 bytes in 34 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[question] 我爱你中国
	[proc_synonym] 爱 -> []
	[proc_synonym] 中国 -> ['途中']
MaxSimIndex_list [105, 12, 108]
[index_list] [105, 12, 108]
[2018-01-13 22:58:05,846] ERROR in app: Exception on /smartQuestion [GET]
Traceback (most recent call last):
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/pymysql/connections.py", line 920, in connect
    **kwargs)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zwm/Workplace/SmartStation/flask/src/main.py", line 27, in get_answer
    ans = answer(question)
  File "/home/zwm/Workplace/SmartStation/flask/src/qa.py", line 133, in answer
    answers = get_answers_from_db(index_list)
  File "/home/zwm/Workplace/SmartStation/flask/src/qa.py", line 151, in get_answers_from_db
    db = pymysql.connect(host=host, user=user, password=password, database=database, charset='utf8') # 连接数据库
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/pymysql/connections.py", line 699, in __init__
    self.connect()
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/pymysql/connections.py", line 967, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '47.94.111.175' (timed out)")
[pid: 6031|app: 0|req: 2/3] 127.0.0.1 () {36 vars in 745 bytes} [Sat Jan 13 22:57:55 2018] GET /smartQuestion?question=%E6%88%91%E7%88%B1%E4%BD%A0%E4%B8%AD%E5%9B%BD => generated 291 bytes in 10346 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
[question] 购票
MaxSimIndex_list [404, 459, 220]
[index_list] [404, 459, 220]
[pid: 6033|app: 0|req: 1/4] 127.0.0.1 () {36 vars in 691 bytes} [Sat Jan 13 22:59:28 2018] GET /smartQuestion?question=%E8%B4%AD%E7%A5%A8 => generated 643 bytes in 801 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[question] 6034
	[proc_synonym] 6034 -> ['12306APP']
MaxSimIndex_list [303, 359, 252]
[index_list] [303, 359, 252]
[pid: 6034|app: 0|req: 1/5] 127.0.0.1 () {36 vars in 663 bytes} [Sat Jan 13 23:00:28 2018] GET /smartQuestion?question=6034 => generated 1211 bytes in 776 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[question] 6034
	[proc_synonym] 6034 -> ['12306APP']
MaxSimIndex_list [303, 359, 252]
[index_list] [303, 359, 252]
[pid: 6033|app: 0|req: 2/6] 127.0.0.1 () {38 vars in 694 bytes} [Sat Jan 13 23:03:19 2018] GET /smartQuestion?question=6034 => generated 1211 bytes in 4246 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 6035)
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.15 (64bit) on [Sat Jan 13 23:03:43 2018] ***
compiled with version: 5.4.0 20160609 on 04 December 2017 23:48:23
os: Linux-4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017
nodename: o-ubuntu-o
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/zwm/Workplace/SmartStation/flask/conf
writing pidfile to /home/zwm/Workplace/SmartStation/flask/log/uwsgi.pid
detected binary path: /home/zwm/Workplace/SmartStation/venv-py3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 14759
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:5000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:43887 (port auto-assigned) fd 3
Python version: 3.5.2 (default, Sep 14 2017, 22:51:06)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x2278100
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 670995 bytes (655 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x2278100 pid: 6299 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 6299)
spawned uWSGI worker 1 (pid: 6302, cores: 1)
spawned uWSGI worker 2 (pid: 6303, cores: 1)
spawned uWSGI worker 3 (pid: 6304, cores: 1)
spawned uWSGI worker 4 (pid: 6305, cores: 1)
spawned uWSGI http 1 (pid: 6306)
[question] 6034
MaxSimIndex_list [477, 698]
[index_list] [477, 698]
[pid: 6302|app: 0|req: 1/1] 127.0.0.1 () {38 vars in 694 bytes} [Sat Jan 13 23:03:47 2018] GET /smartQuestion?question=6034 => generated 115 bytes in 5206 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[question] 6034
MaxSimIndex_list [477, 698]
[index_list] [477, 698]
[pid: 6304|app: 0|req: 1/2] 127.0.0.1 () {38 vars in 694 bytes} [Sat Jan 13 23:07:57 2018] GET /smartQuestion?question=6034 => generated 115 bytes in 1554 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[question] 6034啥时候发车
MaxSimIndex_list [698, 477, 561]
[index_list] [698, 477, 561]
[pid: 6305|app: 0|req: 1/3] 127.0.0.1 () {36 vars in 753 bytes} [Sat Jan 13 23:08:31 2018] GET /smartQuestion?question=6034%E5%95%A5%E6%97%B6%E5%80%99%E5%8F%91%E8%BD%A6 => generated 169 bytes in 1194 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[question] 车站
MaxSimIndex_list [60, 36, 106]
[index_list] [60, 36, 106]
[pid: 6305|app: 0|req: 2/4] 127.0.0.1 () {36 vars in 691 bytes} [Sat Jan 13 23:14:55 2018] GET /smartQuestion?question=%E8%BD%A6%E7%AB%99 => generated 1619 bytes in 2264 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[question] 车站洗手间
	[proc_synonym] 洗手间 -> ['手续费']
MaxSimIndex_list [60, 36, 106]
[index_list] [60, 36, 106]
[pid: 6302|app: 0|req: 2/5] 127.0.0.1 () {36 vars in 745 bytes} [Sat Jan 13 23:15:03 2018] GET /smartQuestion?question=%E8%BD%A6%E7%AB%99%E6%B4%97%E6%89%8B%E9%97%B4 => generated 1619 bytes in 527 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[question] 存包处
	[proc_synonym] 存 -> []
	[proc_synonym] 包 -> ['包裹']
	[proc_synonym] 处 -> ['处理']
MaxSimIndex_list [2, 26, 121]
[index_list] [2, 26, 121]
[pid: 6304|app: 0|req: 2/6] 127.0.0.1 () {36 vars in 709 bytes} [Sat Jan 13 23:15:12 2018] GET /smartQuestion?question=%E5%AD%98%E5%8C%85%E5%A4%84 => generated 1721 bytes in 1222 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 6306)
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.15 (64bit) on [Sun Jan 14 09:07:08 2018] ***
compiled with version: 5.4.0 20160609 on 04 December 2017 23:48:23
os: Linux-4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017
nodename: o-ubuntu-o
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/zwm/Workplace/SmartStation/flask/conf
writing pidfile to /home/zwm/Workplace/SmartStation/flask/log/uwsgi.pid
detected binary path: /home/zwm/Workplace/SmartStation/venv-py3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 14759
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:5000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:36427 (port auto-assigned) fd 3
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1d85180
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 670995 bytes (655 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x1d85180 pid: 18869 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 18869)
spawned uWSGI worker 1 (pid: 18873, cores: 1)
spawned uWSGI worker 2 (pid: 18874, cores: 1)
spawned uWSGI worker 3 (pid: 18875, cores: 1)
spawned uWSGI worker 4 (pid: 18876, cores: 1)
spawned uWSGI http 1 (pid: 18877)
[question] k1082
	[proc_synonym] k1082 -> ['6031']
MaxSimIndex_list [601]
[index_list] [601]
[2018-01-14 09:07:43,929] ERROR in app: Exception on /smartQuestion [GET]
Traceback (most recent call last):
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/pymysql/connections.py", line 920, in connect
    **kwargs)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zwm/Workplace/SmartStation/flask/src/main.py", line 27, in get_answer
    ans = answer(question)
  File "/home/zwm/Workplace/SmartStation/flask/src/qa.py", line 133, in answer
    answers = get_answers_from_db(index_list)
  File "/home/zwm/Workplace/SmartStation/flask/src/qa.py", line 151, in get_answers_from_db
    db = pymysql.connect(host=host, user=user, password=password, database=database, charset='utf8') # 连接数据库
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/pymysql/connections.py", line 699, in __init__
    self.connect()
  File "/home/zwm/Workplace/SmartStation/venv-py3/lib/python3.5/site-packages/pymysql/connections.py", line 967, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '47.94.111.175' ([Errno 101] Network is unreachable)")
[pid: 18876|app: 0|req: 1/1] 127.0.0.1 () {36 vars in 665 bytes} [Sun Jan 14 09:07:43 2018] GET /smartQuestion?question=k1082 => generated 291 bytes in 458 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
[pid: 18873|app: 0|req: 1/2] 127.0.0.1 () {36 vars in 617 bytes} [Sun Jan 14 09:07:44 2018] GET /favicon.ico => generated 233 bytes in 39 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 18877)
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
